### ISSUE TITLE
[Question] Is there a way to run all organizers?

### ISSUE THREAD

**Issue by Cotspheer** [jsebold666/RazorEnhanced#103]
As the title says, it is a chore to run all organizers one by one. Keybinding works only to a degree but one wants to empty its pocket in one click. Is there a good way to do that?

Maybe as a feature request:
Is it possible to give the organizer the same possibility like the autoloot-agent using different bags within one list? So I could setup my backpack as my source and instead a destination for the whole list I could set the destination per item. This way it would allow me to empty my backpack directly to different containers in my bank.

Thanks for your time in advance!

No hard feelings if you close the ticket if this is the wrong place to ask :).

**Comment by cesare-montresor** [comment]
Hello Thomas,

You are most welcome to post issues and suggestions here. Eventually we
also have a dedicated discord forum for it, in case you keen in faster
discussion.

Anyway, i'm not too sure if this fits your need, but you could try this one:

https://razorenhanced.github.io/doc/api/Organizer.html#M-Organizer-RunOnce

Il lun 22 mag 2023, 00:16 Thomas Erni ***@***.***> ha scritto:

**Comment by Cotspheer** [comment]
Well I didn't think of that! Sure that helps a lot. So I can just create a small script and run the organizers all at once. Sometimes the simplest solutions are hidden right in front of one!
