### ISSUE TITLE
Windows 11 guaranteeing loader.dll

### ISSUE THREAD

**Issue by BreakQuick** [jsebold666/RazorEnhanced#126]
My Windows 11 is guaranteeing the file loader.dll causes a client load fail.

**Comment by BreakQuick** [comment]
Says this is found
Trojan:Win32/Wacatac.B!ml
Effected file
file: C:\Program Files (x86)\ClassicUOLauncher\ClassicUO\Data\Plugins\RazorEnhanced\Loader.dll

**Comment by credzba** [comment]
Sometimes windows decides RE is a virus, but the code is open, and so long
as you're getting it from our site, or github, I believe it is safe.

I dont have the money to buy a MS developer license

**Comment by BreakQuick** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:Aptos;
	panose-1:2 11 0 4 2 2 2 2 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.EmailStyle19
	{mso-style-type:personal-reply;
	font-family:"Calibri",sans-serif;
	color:windowtext;}
MsoChpDefault
	{mso-style-type:export-only;
	font-size:10.0pt;
	mso-ligatures:none;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by BreakQuick** [comment]
sorry replied by outlook
Hey Felix
Thanks for the reply.

I feel totally safe using it, it was more the latest update triggered it, and letting you know. I rolled back two versions and everything works fine, I had to do a full re-install for some reason, but wasn’t that big a deal.
 
How much does a MS developer license cost out of interest?

**Comment by credzba** [comment]
LOL outlook is a mess!

Last I checked it's like 300$ a year, but I may ne wrong

**Comment by BreakQuick** [comment]
Is razor enhanced yours?

**Comment by credzba** [comment]
I own the repository, but some other devs also contribute

**Comment by BreakQuick** [comment]
But in theory it's yours, if i can help anyway let me know, I am not develepper, would a license help?

**Comment by credzba** [comment]
We need to research if the license is enough to stop the virus warnings.
It is expensive, and if its only 1 year of relief, its not worth the
expense.

**Comment by BreakQuick** [comment]
Let me know, are you clued up on Dust CUO client?

**Comment by cesare-montresor** [comment]
We could potentially publish it in the M$ store, it's 19$ one-time off and
should make it trusted

Il lun 29 gen 2024, 11:31 BreakQuick ***@***.***> ha scritto:

**Comment by credzba** [comment]
Dusty used to post with RazorEnhanced community a lot.
I haven't seen him in a while, but he is a good person

**Comment by credzba** [comment]
I like this idea!

**Comment by BreakQuick** [comment]
ok what can i do?
send link

**Comment by credzba** [comment]
At this point, I think nothing, I need to make RE use a ms installer, and
then we can see if ms store will accept it

**Comment by BreakQuick** [comment]
Np Hit me up if you need anything

**Comment by BreakQuick** [comment]
Can i ask a question, why does auto bandage work on normal client but not on CUO?

**Comment by credzba** [comment]
should work on both
