### ISSUE TITLE
journal check not seeing system message

### ISSUE THREAD

**Issue by ngyoung** [jsebold666/RazorEnhanced#13]
If I add a rune to a runebook the client automatically makes a system message with the name of the rune.  When testing with a rune named "Abyss E" the if injournal would not trigger when that name was seen in the journal.  There is a workaround that works by leaving off 'system' but that isn't ideal.  Some uses a script could get false triggers from other players instead of only the system if that filter is removed.  I don't know how many other 'system' type messages are not being recognized as coming from the system.

![image](https://user-images.githubusercontent.com/84091873/118292611-6e1a9380-b49e-11eb-86ef-e8a5a09c0f77.png)

The following is a small test script i ran after manually added a rune named "Abyss E".

```
if @injournal 'Abyss E' 'system'
  headmsg 'Rune added!'
else
  headmsg 'failed'
endif
```

**Comment by credzba** [comment]
Problem was the system attribute was not being associated with that message. 
Should be fixed in  7.7.23 / 8.0.5
