### ISSUE TITLE
pathfind issues

### ISSUE THREAD

**Issue by pkrion** [jsebold666/RazorEnhanced#130]
sometimes client freezes using pathfind
![image](https://github.com/RazorEnhanced/RazorEnhanced/assets/20083111/9363e4dd-2169-4699-911b-35757319abf4)

other times it just keep waiting for ever could be possible add somekind of timeout please? tyvm for all your work

im using it in this way:

def pathfindToCoord(coords):
    coord = PathFinding.Route()
    coord.StopIfStuck = True
    coord.IgnoreMobile = True
    coord.X=coords[0]
    coord.Y=coords[1]
    coord.MaxRetry=5
    coord.DebugMessage=True
    coord.UseResync=True
    if PathFinding.Go(coord):
        pass

**Comment by sayotte** [comment]
`PathFinding.Route` does have a timeout option, e.g.:
```python
# Example: near Nujel'm Bank
dst_X = 3762
dst_Y = 1301

route = PathFinding.Route()
route.X = dst_X
route.Y = dst_Y
route.MaxRetry = -1
route.Timeout = 5
route.IgnoreMobile = True
route.StopIfStuck = False
route.DebugMessage = True
route.UseResync = True

if PathFinding.Go(route):
    Misc.SendMessage("Arrived",170)
else:
    Misc.SendMessage("Not Arrived", 138)
```
