### ISSUE TITLE
targetexists 'any/harmful/beneficial' does not work

### ISSUE THREAD

**Issue by ngyoung** [jsebold666/RazorEnhanced#15]
Steam can distinguish between spell targets that are harmful/attacking spells and ones that are deemed beneficial, that heal, cure, or buff the target.  RE doesn't appear to see the cursor at all even when you put in 'any'.  It will trigger both if conditions in the following script with or without a target cursor:
```
//UOS
if targetexists 'harmful'
  headmsg 'Negative Spell'
endif
if targetexists 'beneficial'
  headmsg 'Friendly Spell'
endif
```
Taking of the 'harmful/beneficial' which should act the same as using 'any' throws an error
[15:20:39] - Generic Error:
[15:20:39] - Traceback (most recent call last):
[15:20:39] - SystemError: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

Putting in any word after targetexists allows the script to run but still doesn't respect the if condition and will execute it even if you don't have a target cursor up.
```
if targetexists 'whateverWord"
  headmsg 'I have a target'
endif  
```

**Comment by credzba** [comment]
Yeah,  Dalamar did something with targeting, but it isn't handled exactly like UOS .. This may be a tough one

**Comment by ngyoung** [comment]
> Yeah, Dalamar did something with targeting, but it isn't handled exactly like UOS .. This may be a tough one
CUO uses a red, blue, or grey coloring for targets to represent harmful, beneficial, or neutral.  Can you take advantage of that same info to assign the target type?

**Comment by d0tsd0tsd0ts** [comment]
@credzba it can be closed..

**Comment by credzba** [comment]
close per  dots
