### ISSUE TITLE
Update has shrunken the login window

### ISSUE THREAD

**Issue by BreakQuick** [jsebold666/RazorEnhanced#155]
Hi 
Recent update has shrunk the login window. 
I have changed nothing else except updated RE
![Screenshot 2024-09-08 at 22 15 11](https://github.com/user-attachments/assets/2e087935-19e0-44c0-8c74-64b691b9b147)

**Comment by credzba** [comment]
I have an idea what might cause it. I'll post an update in a couple hours

**Comment by BreakQuick** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Aptos;
	panose-1:2 11 0 4 2 2 2 2 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:12.0pt;
	font-family:"Aptos",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.EmailStyle19
	{mso-style-type:personal-reply;
	font-family:"Aptos",sans-serif;
	color:windowtext;}
MsoChpDefault
	{mso-style-type:export-only;
	font-size:10.0pt;
	mso-ligatures:none;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
