### ISSUE TITLE
Inspect Entities/Houses

### ISSUE THREAD

**Issue by KuruptJester** [jsebold666/RazorEnhanced#16]
performing inspect entities on a house floor tile will show the X Y Z of the tile but not the GFX. It grabs more information from the floor below the house tile (grass, snow, desert, etc.)

performing a record does work properly and gets the GFX code as part of the target code but this is a long way around in my opinion.

**Comment by credzba** [comment]
I looked into this a little, and I think it is caused by RE not handling dynamic static changes properly. 
Should be fixed, but needs more research / time.

**Comment by credzba** [comment]
This may be fixed, but I am not working on it now so closed
