### ISSUE TITLE
Make Assist able to open even when the game is playing

### ISSUE THREAD

**Issue by JXYKA** [jsebold666/RazorEnhanced#160]
Pls make Assist able to detect and use on a running client instead of only starting up with it. Right now I'm unable to use this client because of mandatory custom launcher which will always disable the launching of Assist when the game starts. There's no way to use it even I so want to. Open to other options as long as it can function.

I've tried to open the .dll and edit the setting.json.. It cannot work as the launcher will always change it back before launch. Pls help.

**Comment by credzba** [comment]
Ask in discord channel.
This is not w place to discuss your issues
