### ISSUE TITLE
ignoreobject does not appear to be working

### ISSUE THREAD

**Issue by ngyoung** [jsebold666/RazorEnhanced#17]
Running the following script that uses ingoreobject 'found'.  It gets stuck clicking on the same object when it should click it one time and if it a keyword isn't found in a journalcheck it should ignore it and go back to the beginning of the while loop.

This script in UOS will look for any runebook in my backpack and if it has the title "Home" in it, assign it to an alias "home1" to reference with other scripts to recall home by targeting the alias "home1".  In RE it gets stuck single clicking the same runebook that doesn't have the name "Home" in the title and won't move on to another book.

```
//UOS
@clearjournal
if not findobject 'home1'
  unsetalias 'home1'
  clearignorelist
  if not findalias 'home1'
    headmsg 'reading'
    while findtype 0x22c5 'any' 'backpack'
      clickobject 'found'
      pause 300
      if injournal "Home" 'system'
        setalias 'home1' 'found'
        break
      else
        ignoreobject 'found'
        pause 300
      endif
    endwhile
  endif
endif
```
![image](https://user-images.githubusercontent.com/84091873/119037454-9d864000-b977-11eb-9ef0-2fa4281a994c.png)

**Comment by credzba** [comment]
Correction is checked in, and will be in builds 0.7.7.27 & 0.8.0.9
