### ISSUE TITLE
PathFinding Bugs with Classic UO client

### ISSUE THREAD

**Issue by weteamsteve** [jsebold666/RazorEnhanced#18]
Using ClassicUO client, there is skipping while using PathFinding Route like
```
def go(x1, y1,):
    Coords = PathFinding.Route() 
    Coords.X = x1
    Coords.Y = y1
    Coords.MaxRetry = 5
    PathFinding.Go(Coords)
```

To get around using that pathfinding, when trying to use 
```
def go(x1, y1,):
        z1 = Player.Position.Z
        Player.PathFindTo(x1, y1, z1)
        safeexit = 0
        while Player.Position.X != x1 and Player.Position.Y != y1 and Player.Position.Z != z1 and safeexit < 500:
            safeexit += 1
            Misc.Pause(50)
```
with
```
        rail = [[108, 74], [102, 84]]
        for coord in rail: 
            go(coord[0],coord[1])
```
it immediately locks up. The locations are valid and nearby... don't have a Z values, so trying to use `Player.Position.Z`

**Comment by credzba** [comment]
I recently fixed many pathfinding issues. try 8.2.26 and open new bug if still failing.
In testing I ran from Brit moongate to destard and from furthest south to Yew city
