### ISSUE TITLE
walking directs off by along way....

### ISSUE THREAD

**Issue by yoda29369** [jsebold666/RazorEnhanced#19]
walking is a a serious issue.... i think u may have directionals off...ie when its meant to move one way it moves the other see uosteam scrypt below////

 while not @inrange 'reg' 1
      @clickobject 'reg'
      if @x 'found' > x 'self' and @y 'reg' > y 'self'
        run 'Southeast'
      elseif @x 'reg' < x 'self' and @y 'reg' > y 'self'
        run 'Southwest'
      elseif @x 'reg' > x 'self' and @y 'reg' < y 'self'
        run 'Northeast'
      elseif @x 'reg' < x 'self' and @y 'reg' < y 'self'
        run 'Northwest'
      elseif @x 'reg' > x 'self' and @y 'reg' == y 'self'
        run 'East'
      elseif @x 'reg' < x 'self' and @y 'reg' == y 'self'
        run 'West'
      elseif @x 'reg' == x 'self' and @y 'reg' > y 'self'
        run 'South'
      elseif @x 'reg' == x 'self' and @y 'reg' < y 'self'
        run 'North'
        @clickobject 'reg'
      endif
      if @inrange 'reg' 2
        moveitem 'found' 'backpack' (0 0 0) 'any'
        pause 250
        for 0 to 3
          headmsg 'I have found the arty' 33 'self'
          pause 250
        endfor
        @unsetalias 'reg'
        @unsetalias 'found'
        waitforcontext 0x40f5a183 2 15000
        waitforgump 'magekeys' 15000
        @replygump 0x6abce12 0
      endif
    endwhile
  endwhile

**Comment by credzba** [comment]
The problem with this script is it doesn't take into account that if your not facing the direction you ask to move, the first run just changes your direction.  so you need something like : 
if @x 'found' > x 'self' and @y 'reg' > y 'self'
turn 'Southeast' 
run 'Southeast'
elseif @x 'reg' < x 'self' and @y 'reg' > y 'self'
turn 'Southwest'
run 'Southwest'

**Comment by yoda29369** [comment]
sorry that totally wrong used in many many scrypts on uos....  the target found is an item that is  an item its looking for,,,,not need to turn wen walking as commands do it...ur saying if facing east u cant run  west  ...wrong

**Comment by credzba** [comment]
I don't mean you can't, I mean the first step just turns, second and later
will walk.

But in my testing, the direction was correct

**Comment by yoda29369** [comment]
send the full  scrypt  u use to my disco plz...it dont add up

**Comment by yoda29369** [comment]
ok.. rechecked the uos walking to re walking ...definately off.....by a long way heresmy working copy of uos directly pasted in re.

//uos
unsetalias 'chest'
while @findtype '0x13b4' 'any' 'ground' 'any' 12
  pause 250
  @setalias 'chest' 'found'
  for 0 to 3
    pause 250
    sysmsg 'chest in the area'
    headmsg 'arty in the area'
  endfor
  while not @inrange 'chest' 1
    @clickobject 'arty'
    if @x 'chest' > x 'self' and @y 'chest' > y 'self'
      walk 'Southeast'
    elseif @x 'chest' < x 'self' and @y 'chest' > y 'self'
      walk 'Southwest'
    elseif @x 'chest' > x 'self' and @y 'chest' < y 'self'
      walk 'Northeast'
    elseif @x 'chest' < x 'self' and @y 'chest' < y 'self'
      walk 'Northwest'
    elseif @x 'chest' > x 'self' and @y 'chest' == y 'self'
      walk 'East'
    elseif @x 'chest' < x 'self' and @y 'chest' == y 'self'
      walk 'West'
    elseif @x 'chest' == x 'self' and @y 'chest' > y 'self'
      walk 'South'
    elseif @x 'chest' == x 'self' and @y 'chest' < y 'self'
      walk 'North'
      @clickobject 'chest'
    endif
  endwhile
  if @inrange 'chest' 1
    for 0 to 3
      sysmsg 'Im in range to pick the lock' 33
    endfor
    @unsetalias 'chest'
    @unsetalias 'found'
  endif
endwhile

**Comment by yoda29369** [comment]
elseif @x 'chest' > x 'self' and @y 'chest' < y 'self'
walk 'Northeast'         this line seems to be main  issue

**Comment by ngyoung** [comment]
I pulled out the snippet for my UOS taming script that follows animals that I am taming.  It works as intended and has the same directional logic that yours has.  I modified your script to find the ID of a chest I had on the ground and I always ran NW from the item instead of towards it, no matter which direction I was relative to the chest when starting the script.  I then modified the findtype to the ID of a wandering animal and it followed the animal as intended.  So something is different with determining location of items on the ground relative to self as opposed to other mobiles.   Mobiles it seems to determine relative location just fine but items it does not. I tried several different items inside and outside of my house.

**Comment by yoda29369** [comment]
in uos works perfectly static and animals....hmm i''ll rebulld whole scrypt and retargetting via uos then repost on re found issues that shudn't work anyway....    *** .devs please do not alter anything in walking yet**

**Comment by yoda29369** [comment]
redone whole scrypt....   smaller version....... does not work.......one line of movement ..glad 2 people have had same faults now....
i have disected all movement...... its broken...somehow...
if @findtype '0x13b4' 'any' 'ground' 'any' 12
  pause 250
  @setalias 'chest' 'found'
endif 
debug 'on' 
  //endfor
  //put movement here
 if not inrange 'chest' 1
    @clickobject 'chest'
    pause 500
    while x 'chest' == x 'self' and y 'chest' > y 'self'
    pause 250
    walk 'South'
    endwhile
  endif
  replay

**Comment by yoda29369** [comment]
should walk south btw

**Comment by credzba** [comment]
Try latest update. Locations fixed
