### ISSUE TITLE
Pause required between waitforgump and replygump.

### ISSUE THREAD

**Issue by ngyoung** [jsebold666/RazorEnhanced#22]
I don't know the exact best way to handle this, if at all by the interpreter, but between the action of waitforgump and reply gump it seems like there is not enough time between when the gump appears and when replygump executes.  For my computer, if I put in a "pause 30" after waitforgump line I get a consistent performance.  Going to 20 it works half the time and eventually not at all as I reduce the pause.  I am suspecting that RE sees that a gump exists but there is still a small moment where the selections haven't loaded still for replygump to successfully complete.  I am thinking that maybe there should be a fraction of time that the gump needs to exist before it stops waiting.
```
//UOS
while @findtype 0xe9b 'any' 'backpack'
  @clearjournal
  useobject 'found'
  waitforgump 0x38920abd 15000
  headmsg 'reply gump make last'
  replygump 0x38920abd 21
  pause 2000
endwhile
//
headmsg 'ALL DONE!!'
```

**Comment by credzba** [comment]
I could add a hard coded delay after the wait completes, but that seems wrong.  The python scripts use the exact same logic, and do not need additional delay.  I am going to test a bit more with this.
---
I tried for 10 times, and it always worked properly. 
I may need to visit your server and try a specific combination.  It really should not need an additional pause

**Comment by ngyoung** [comment]
I know we have had other issues with how RE scans gumps with CUO on UOForever server.  Like the champ score gump constantly refreshes and messes up scripts that scan gump contents.  Are you testing with CUO or the standard client?  That may be the other reason the script works fine with UOS and not with RE.

If it is just something people will have to live with I am fine with that.  It may be worth creating a list of little things like this for a UOS scripts in RE Troubleshooting page.
