### ISSUE TITLE
Out of bound selected index of script view crashes razor

### ISSUE THREAD

**Issue by vehumet** [jsebold666/RazorEnhanced#63]
How to reproduce:
1. Let profile A has 10 scripts and B has 20 scripts.
2. B selects any script that has index of 11~20, then change profile to A
3. Razor crashes

https://github.com/RazorEnhanced/RazorEnhanced/blob/691ad85ffa40a8f31682d2f1c26a18f6cb346d83/Razor/UI/Other/Script.cs#L134

I think `currentSelectedIndex` of above code makes out of bound exception.

**Comment by credzba** [comment]
Thank you for excellent decription of problem. 
I have committed the fix to the main branch, and this coming weekend I'll build and deploy the update.
If you need it sooner, let me know and I'll build just for this fix
