### ISSUE TITLE
vendor.buy not buying item by count

### ISSUE THREAD

**Issue by weteamsteve** [jsebold666/RazorEnhanced#68]
`Vendor.Buy(shop.Serial, item_id, count)` isn't working like it used to (pre june 2021?)

for example, if trying to purchase 20 runes from a vendor, only buys 1 now

**Comment by credzba** [comment]
I just tested this buying arrows, works properly. 
Tested on 8.2.26

**Comment by credzba** [comment]
What version RE you running. This was an old bug I thought was fixed
