### ISSUE TITLE
`while not buffexists 'consecrate weapon'`

### ISSUE THREAD

**Issue by yoda29369** [jsebold666/RazorEnhanced#7]
using the `while not` and `if not`     the re is not reading the negative so constantly carry out the action uos>> re

Davon

**Comment by yoda29369** [comment]
''settimer ''0''      ..does not work rest of timer scrypts seem to work

**Comment by credzba** [comment]
Looks like Dalamar fixed the settimer 0, and the buffexists was working, but the spelling was not exact .. I made the compare more flexible so that it can guess whatever buff spelling you use, so long as your close" 
Should be fixed in 7.7.23 & 8.0.5

**Comment by yoda29369** [comment]
buffs exist work well checked and tried..timers are broken and so is walking techniquies
`settimer 'sample' '0'`
`settimer 'sample'`           both do not work

**Comment by yoda29369** [comment]
with or without quotes
