### ISSUE TITLE
ClassicUO and RazorEnhanced Both Trying To Send Packets, Random Disconnects

### ISSUE THREAD

**Issue by weteamsteve** [jsebold666/RazorEnhanced#70]
After a little debugging with Credzba and random old related messages on ClassicUO and RazorEnhanced discord people think it is an issue with RE and CUO sending packets, maybe a race condition. Happens to me while running rails (pathfinding) and crafting.

"This is the disconnect message, but you may be write. It may be when both RE and CUO are trying to send a packet"

```
System.Net.Sockets.SocketException (0x80004005): An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at ClassicUO.Network.NetClient.ProcessSend() in C:\ClassicUO\src\Network\NetClient.cs:line 539
09/22/2022 01:38:50 |   Trace    | Disconnected [game socket]
09/22/2022 01:38:58 |   Trace    | Saving path:         C:\ClassicUO\bin\Debug\Data\Profiles\account\server\character
09/22/2022 01:38:58 |   Trace    | Saving done!
09/22/2022 01:38:58 |   Warning  | PlayerMobile disposed!
09/22/2022 01:38:58 |   Error    | Attempt to write into a dead socket
```

I know it is kind of hard to truly pin down this problem with perfect evidence but I think resolving this multi-year plus issue would be big for a lot of people. Going to try to debug/get any data I can.

@credzba has tried a mutex fix and seeing if problem happens again

**Comment by weteamsteve** [comment]
believe you can reproduce it by 

```
fil = Mobiles.Filter()
fil.Enabled = True
fil.RangeMax = 15

while True:
    mob = Mobiles.ApplyFilter(fil)
    for e in mob:
        Misc.SendMessage(e.Serial)
        Mobiles.WaitForStats(e,100)
        Misc.Pause(10)
```

in a crowded place and spam it
can change pause to 50, it should dc fairly quick, credit to Ascyx#8731 aka Onoquoy

**Comment by lbhk** [comment]
This problem started with 0.8.0.39, 0.8.0.38 is just fine

**Comment by to-sh-1** [comment]
Would love it if this is the reason I d/c so much, unfortunately this script isn't disconnecting me at wbb (yet)
How are you able to get that disconnect message?  My error logs don't show anything when I disconnect

**Comment by wtfuzzy** [comment]
This is still happening on current builds. However, I think we can safely say it's due to both processes sending packets at the same time. I'm observing it with my local ServUO instance, and on the server side, it reports "Player using godclient, disconnecting". The godclient protection kicks in under exactly that circumstance: Packet being received while another is being processed for the same NetState (connection).

**Comment by bittiez** [comment]
Still happening, it's really killing the game for me, I've played too long with macros so I can't go back to not using an assistant, but good god I can't get through one or two dragons before being disconnected. As @toshiSat said I don't get actually disconnected, I can still see my hits going down, but none of the packets from my client are doing anything, can't move/heal/attack, I just have to log out and back in, hoping I make it in time to not die.

**Comment by credzba** [comment]
Quit using CUO. I know it's prettier, but I can't stand it's disconnect
either

**Comment by Dramoor** [comment]
To be fair, This issue should be fixed in newer versions of CUO. Also, servers will disconnect you if you try to do 2 delay actions at the same time. So if you try to attack two mobs at the same time. The server itself will disconnect you in most instances.
