### ISSUE TITLE
Mono Linux detect bug

### ISSUE THREAD

**Issue by P4cm4n90** [jsebold666/RazorEnhanced#77]
When I run RazorEnhanced using mono I get this error
![image](https://user-images.githubusercontent.com/50337469/203301927-7cfd3b8b-8bb0-4044-a0ba-e652d9f548aa.png)
I found out that problems lays in the Settings.cs:
![image](https://user-images.githubusercontent.com/50337469/203302088-2044ed25-9d2e-4ab8-9c48-ac129224b411.png)
In default configuration there is no key LocalMachine\\Software\\Wine\\Drives

We can fix this by adding registry key Drives to LocalMachine\\Software\\Wine\\ or modyfing the code.
My advice:
Change line 405: localKey.OpenSubKey("Software\\Wine\\Drives") to localKey.OpenSubKey("Software\\Wine")

**Comment by ImmRanneft** [comment]
have you been able to fix that and comiple correct version?
